package com.practiceproject.EmployeeManagementSystem.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import com.practiceproject.EmployeeManagementSystem.service.EmployeeService;

@Controller//Thay bang controller vi restcontroller thi khong hien dc trang chu
public class EmployeeController {
    @Autowired 
    // This means to get the bean which is auto-generated by Spring
	// We will use an employeeService for each
    private EmployeeService service;
    //Hiển thị trang chủ
    @GetMapping("/")
    // This means that this method will be executed when user sends GET Requests to "/"
	// In our case, "http://localhost:8080/"
    public String getEmployees(Model model){
        model.addAttribute("ListEmployees", service.getEmployees());
        return "homepage";
    }
}
